name: Business Central On-Premises Feature Branch CI

on:
  repository_dispatch:
    types: [issue_updated]



jobs:
  setup-repo:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with: 
          repository: KRYAYKN/BCN

   

  build:
    needs: setup-repo
    runs-on: [ self-hosted ]
    steps:
      - name: Setup Docker for Business Central On-Premises Sandbox
        run: |
          install-module BCContainerHelper -force
          Write-BCContainerHelperWelcomeText
          $artifactUrl = Get-BcArtifactUrl -type sandbox -country us -select Latest New-BCContainer -accept_eula -containerName mysandbox -artifactUrl $artifactUrl
        
      - name: Compile AL Project
        run: |
          cd src
          docker exec bcsandbox-onprem powershell -Command "C:/scripts/run-al-compile.ps1 -ProjectPath 'C:/src/MyBCProject'"

  test:
    needs: build
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with: 
          repository: KRYAYKN/BCN

      - name: Run Unit Tests
        run: |
          docker exec bcsandbox-onprem powershell -Command "C:/scripts/run-tests.ps1 -TestSuiteName 'DEFAULT'"

  publish:
    needs: test
    if: success()
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with: 
          repository: KRYAYKN/BCN

      - name: Publish to Business Central On-Premises Sandbox
        run: |
          docker exec bcsandbox-onprem powershell -Command "C:/scripts/publish-app.ps1 -AppPath 'C:/src/MyBCProject/*.app' -Environment 'Sandbox'"
